### ISSUE TITLE
Ringbuffer does not work on STM32F4xx boards

### ISSUE THREAD

**Issue by Omcsesz** [HansPeterHaastrup/STM32Ringbuffer#1]
Hello, Hans!

When I tried to use your code by changing #include "stm32f7xx_hal.h" to #include "stm32f4xx_hal.h" in the header file, but then, I got some errors:
'USART_ISR_RXNE' undeclared (first use in this function)
'USART_ISR_TXE' undeclared (first use in this function)
'USART_TypeDef {aka struct <anonymous>}' has no member named 'ISR'; did you mean 'SR'?	
'USART_TypeDef {aka struct <anonymous>}' has no member named 'ISR'; did you mean 'SR'?	
'USART_TypeDef {aka struct <anonymous>}' has no member named 'ISR'; did you mean 'SR'?	
'USART_TypeDef {aka struct <anonymous>}' has no member named 'RDR'; did you mean 'DR'?	
'USART_TypeDef {aka struct <anonymous>}' has no member named 'TDR'; did you mean 'DR'?	

Can I modify the RDR (read data register) and TDR (transmit data register) both to DR (data register)? It seems incorrect.

**Comment by HansPeterHaastrup** [comment]
The architecture on the 7xx and the 4xx families differ. These are some of the changes I made to get the system to work on my 746 controller.

If you look at the original code (https://controllerstech.com/ring-buffer-using-head-and-tail-in-stm32/)

you will see tthat SR and DR is the ones used:

`huart->Instance->SR;
    	      huart->Instance->DR = c;`

So apparently the DR register is used for sending and receiving..
